file_format: "1"
id: tbk_mini
name: TBK-Mini
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
siblings:
  - corne_left
  - corne_right
